version: 2.0

jobs:
  lint:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: ls -l
      - run: ./gradlew test
  test:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: ./gradlew test
    store_test_results:
      path: build/test-results
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: ./gradlew jar
      - store_artifacts:
          path: build/libs
          destination: libs

workflows:
  version: 2
  main:
    jobs:
      - lint
      - test:
          requires:
            - lint
  deploy:
    jobs:
      - lint:
          type: approval
      - test:
          requires:
            - lint
      - build:
          requires:
            - test