version: 2.0

jobs:
  lint:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: ls -l
      - run: ./gradlew test
  test:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: ./gradlew test
      - run: ls domain/build/test-results/test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: ./gradlew jar
      - store_artifacts:
          path: build/libs
          destination: libs

workflows:
  version: 2
  main:
    jobs:
      - lint
      - test:
          requires:
            - lint
  deploy:
    jobs:
      - lint:
          type: approval
      - test:
          requires:
            - lint
      - build:
          requires:
            - test